spring:
  application:
    name: lu-api-gateway
  cloud:
    gateway:
      routes:
      - id: qwert
        uri: http://localhost:8123
        predicates:
        - Path=/api/**
#        filters:
#        - AddRequestParameter=name,qwert

server:
  port: 8090

#将 Spring Cloud Gateway 的日志级别设置为 "trace"，这意味着 Spring Cloud Gateway 将输出最详细的日志信息，包括所有的跟踪信息。
#  通过设置这个日志级别，我们可以查看每个请求在网关中的处理流程、断言、过滤器的执行情况以及最终路由的结果，有助于调试和排查问题。 [生产环境要关闭]
logging:
  level:
    org:
      springframework:
        cloud:
          getaway: trace

dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-provider
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22223
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848
